baseURL = "http://dimension.sh/"
languageCode = "en-gb"
title = "dimension.sh"
theme = "dimension"

[params]
style = "nord"


[[params.links]]
[[params.links.link]]
name = "HOME"
href = "/"
[[params.links.link]]
name = "HISTORY"
href = "/history/"
[[params.links.link]]
name = "USERS"
href = "/users/"
[[params.links.link]]
name = "WIKI"
href = "/cgi/wiki.cgi"
[[params.links.link]]
name = "DONATE"
href = "/donate/"
[[params.links.link]]
name = "JOIN"
href = "/join/"