baseURL = "http://dimension.sh/"
languageCode = "en-gb"
title = "dimension.sh"
theme = "dimension"

[params]
style = "nord"

[[params.styles]]
name = "greenscreen"
shortcode = "GS"
[[params.styles]]
name = "palenight"
shortcode = "PN"
[[params.styles]]
name = "dracula"
shortcode = "DC"
[[params.styles]]
name = "nord"
shortcode = "ND"
[[params.styles]]
name = "purple"
shortcode = "PU"

[[params.links]]
name = "HOME"
href = "/"
[[params.links]]
name = "HISTORY"
href = "/history/"
[[params.links]]
name = "USERS"
href = "/users/"
[[params.links]]
name = "WIKI"
href = "/cgi/wiki.cgi"
[[params.links]]
name = "DONATE"
href = "/donate/"
[[params.links]]
name = "FEDI"
href = "https://tilde.zone/@dimension"
rel = "me"
[[params.links]]
name = "JOIN"
href = "/join/"
