# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "dimension"
license = "MIT"
licenselink = "https://github.com/athul/archie/blob/master/LICENSE"
description = "Dimension.sh theme for Hugo"
homepage = "https://github.com/dimension-sh/hugo-dimension"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Andrew Williams"
  homepage = "https://github.com/nikdoof"
