name: Deploy
"on":
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Production
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to target system
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.DIMENSION_DEPLOYMENT_USER }}
          key: ${{ secrets.DIMENSION_DEPLOYMENT_SSH_KEY }}
          port: 22
          script: |
            cd /usr/local/src/www-site
            sudo git config pull.ff only
            sudo git reset --hard
            sudo git pull
            sudo /usr/local/bin/hugo -d /var/www/dimension.sh --gc -b https://dimension.sh/
